[package]
name = "framebuffer-gui"
version = "0.0.1"
authors = ["Carsten Thue-Bludworth <carstentb@protonmail.com>"]
edition = "2021"

[dependencies]
embedded-graphics   = "0.7.1"
framebuffer-display = { path = "../framebuffer-display" }
profont             = "0.6.1"
rand                = "0.8.5"
